---
version: '3.8'
services:
 mydb:
  image: jenkins/jenkins
 ports:
  - 5050:8080
 qaserver:
  image: tomee
  ports:
   - 6060
  networks: -eyz
 prodserver:
  image: tomee
  ports:
   - 7070:8080
  networks:
  abc: {}
  xyz: {}
  